spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:213.108.129.175}:${DB_PORT:5432}/${DATABASE:postgres}?ApplicationName=${jdbcAppName}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:transneft}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2

  jpa:
    properties:
      hibernate:
        default_schema: dictionaries
        dialect: org.hibernate.dialect.PostgreSQLDialect
