spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      dataSourceProperties:
        ApplicationName: "Microservice: ${spring.application.name}"

  jpa:
    properties:
      hibernate:
        default_schema: dictionaries
        dialect: org.hibernate.dialect.PostgreSQLDialect
